# Generated by Django 5.0.2 on 2024-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
