# Generated by Django 5.0.2 on 2024-05-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=200)),
                ('imageTitle', models.FileField(upload_to='news_images')),
                ('firsParagraph', models.TextField()),
                ('secondParagraph', models.TextField()),
                ('thirdParagraph', models.TextField()),
                ('firstImage', models.FileField(upload_to='news_images')),
                ('secondImage', models.FileField(upload_to='news_images')),
                ('thirdImage', models.FileField(upload_to='news_images')),
            ],
            options={
                'db_table': 'News',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categories_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notices.categories')),
                ('news_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notices.news')),
            ],
            options={
                'db_table': 'Categories_and_News',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Users_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notices.news')),
                ('users_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'Users_and_News',
                'ordering': ['id'],
            },
        ),
    ]
