# Generated by Django 5.0.2 on 2024-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='new_date',
            field=models.DateField(null=True),
        ),
    ]
