# Generated by Django 5.0.2 on 2024-05-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_new_new_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='firsParagraph',
            new_name='firstParagraph',
        ),
    ]
