# Generated by Django 5.0.2 on 2024-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_rename_firsparagraph_new_firstparagraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='firstImage',
            field=models.FileField(upload_to='news_python'),
        ),
        migrations.AlterField(
            model_name='new',
            name='imageTitle',
            field=models.FileField(upload_to='news_python'),
        ),
        migrations.AlterField(
            model_name='new',
            name='secondImage',
            field=models.FileField(upload_to='news_python'),
        ),
        migrations.AlterField(
            model_name='new',
            name='thirdImage',
            field=models.FileField(upload_to='news_python'),
        ),
    ]
